#!/bin/bash
# AIDE integrity check with Telegram notifications
#
# The decision to alert is driven by AIDE's EXIT CODE, never by parsing counts
# out of the report. An earlier version of this script grepped for "^Added:",
# which never matches - AIDE writes "Added entries:" - so the counters were
# always zero, the alert branch never fired, and every run reported "no changes"
# and then ran `aide --update`, absorbing any tampering into the baseline.
#
# AIDE exit codes:
#   0        no differences
#   1|2|4    new / removed / changed entries (bitwise OR, so 1..7)
#   >= 14    AIDE itself failed (config error, IO error, version mismatch)

# Credentials live in one place. The values below are only a fallback for
# hosts provisioned before that file existed - a script that holds its own
# copy of a token is one more place to rotate and one more place to leak.
# Single source of truth for credentials. No token is ever written into this
# script: one copy in one root-only file is one place to rotate and one place
# to leak.
# Credentials live with the project checkout, not in /etc. Resolution order:
#   1. $CONFIG_FILE                        explicit override
#   2. $ENV_FILE_DEFAULT                   absolute path recorded at install time
#   3. .env near this script                for running straight from the checkout
#   4. /etc/server-baseline/selfcheck.env  legacy location, still honoured
#
# The recorded path is the fragile part: move or re-clone the project and it
# stops resolving, which would make every alert silently stop. That is why
# security-selfcheck fails outright when no credentials resolve anywhere - the
# breakage shows up within a day instead of as permanent silence.
ENV_FILE_DEFAULT=""   # replaced with an absolute path at install time

resolve_env_file() {
    local self_dir c
    self_dir="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" 2>/dev/null && pwd)" || self_dir=""
    for c in "${CONFIG_FILE:-}" "$ENV_FILE_DEFAULT"              "$self_dir/.env" "$self_dir/../.env" "$self_dir/../../.env"              /etc/server-baseline/selfcheck.env; do
        if [ -n "$c" ] && [ -r "$c" ]; then echo "$c"; return 0; fi
    done
    return 1
}
CONFIG_FILE="$(resolve_env_file || true)"
[ -n "$CONFIG_FILE" ] && . "$CONFIG_FILE"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"

if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
    command -v logger >/dev/null 2>&1 &&         logger -t "$(basename "$0")" "no Telegram credentials in /etc/server-baseline/selfcheck.env; report not sent"
fi
LOG_FILE="/var/log/aide-check-$(date +%Y%m%d).log"
DATE_STAMP=$(date '+%Y-%m-%d %H:%M')

send_telegram() {
    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        -d chat_id="${TELEGRAM_CHAT_ID}" \
        -d text="$1" \
        -d parse_mode="Markdown" >/dev/null 2>&1
}

# Read a count out of AIDE's summary block, e.g. "  Added entries:      3"
summary_count() {
    sed -n "s/^[[:space:]]*$1 entries:[[:space:]]*\([0-9][0-9]*\).*/\1/p" "$LOG_FILE" | head -1
}

# On Debian and Ubuntu, `aide` does NOT read /etc/aide/aide.conf by itself.
# aide-common generates /var/lib/aide/aide.conf.autogenerated and ships
# aide.wrapper to invoke it. A bare `aide --check` fails with "missing
# configuration" (exit 17), which is indistinguishable from a broken config.
#
# This chain must stay identical to the one in security-selfcheck.sh,
# update-baseline.sh, aide-refresh.sh and install-script.sh. It previously did
# not: this copy lacked the /etc/aide/aide.conf branch, fell through to a bare
# `aide`, and reported exit 17 every night on a host whose configuration was
# perfectly fine.
resolve_aide() {
    if command -v aide.wrapper >/dev/null 2>&1; then
        echo "aide.wrapper"
    elif [ -x /usr/sbin/aide.wrapper ]; then
        echo "/usr/sbin/aide.wrapper"
    elif [ -f /var/lib/aide/aide.conf.autogenerated ]; then
        echo "aide --config=/var/lib/aide/aide.conf.autogenerated"
    elif [ -f /etc/aide/aide.conf ]; then
        echo "aide --config=/etc/aide/aide.conf"
    elif [ -f /etc/aide.conf ]; then
        echo "aide --config=/etc/aide.conf"
    fi
}
AIDE="$(resolve_aide)"

# Nothing resolved: say that, rather than running a bare `aide` and reporting
# its exit 17 as though the configuration were at fault.
if [ -z "$AIDE" ]; then
    MESSAGE="🚨 *AIDE CANNOT RUN*%0A%0A"
    MESSAGE+="Server: $(hostname)%0A"
    MESSAGE+="Date: $(date '+%Y-%m-%d %H:%M')%0A%0A"
    MESSAGE+="No usable AIDE configuration was found - no aide.wrapper, no%0A"
    MESSAGE+="generated config, no /etc/aide/aide.conf.%0A%0A"
    MESSAGE+="*File integrity is UNVERIFIED and no scan is being run.*%0A%0A"
    MESSAGE+="Usually means aide-common is not installed:%0A"
    MESSAGE+="\`apt-get install -y aide-common && aideinit\`"
    send_telegram "$MESSAGE"
    exit 1
fi

# Run AIDE check
$AIDE --check > "$LOG_FILE" 2>&1
CHECK_RESULT=$?

if [ "$CHECK_RESULT" -ge 14 ]; then
    # AIDE could not complete. This MUST NOT be reported as "no changes" and the
    # database MUST NOT be updated - a failing integrity checker is an incident
    # in itself, not a clean bill of health.
    MESSAGE="🚨 *AIDE CHECK FAILED*%0A%0A"
    MESSAGE+="Server: $(hostname)%0A"
    MESSAGE+="Date: ${DATE_STAMP}%0A%0A"
    MESSAGE+="⚠️ AIDE exited with code ${CHECK_RESULT} and could not verify anything.%0A"
    MESSAGE+="*File integrity is currently UNVERIFIED.*%0A%0A"
    MESSAGE+="Last output:%0A"
    MESSAGE+="\`$(tail -5 "$LOG_FILE" | tr '\n' ' ' | cut -c1-300)\`%0A%0A"
    MESSAGE+="Full log: \`$LOG_FILE\`"
    send_telegram "$MESSAGE"

elif [ "$CHECK_RESULT" -ne 0 ]; then
    ADDED=$(summary_count Added);     ADDED=${ADDED:-0}
    REMOVED=$(summary_count Removed); REMOVED=${REMOVED:-0}
    CHANGED=$(summary_count Changed); CHANGED=${CHANGED:-0}

    # AIDE detail lines look like "f++++++++++++++++: /path/to/file"
    DETAIL=$(grep -E '^[^[:space:]]+: /' "$LOG_FILE" | head -10 | sed 's/^/• /' | tr '\n' '@' | sed 's/@/%0A/g')

    MESSAGE="🚨 *AIDE Integrity Alert*%0A%0A"
    MESSAGE+="Server: $(hostname)%0A"
    MESSAGE+="Date: ${DATE_STAMP}%0A%0A"
    MESSAGE+="⚠️ *File changes detected!*%0A%0A"
    MESSAGE+="Summary:%0A"
    MESSAGE+="• Added: ${ADDED}%0A"
    MESSAGE+="• Removed: ${REMOVED}%0A"
    MESSAGE+="• Changed: ${CHANGED}%0A%0A"
    MESSAGE+="First entries:%0A${DETAIL}%0A"
    MESSAGE+="Full log: \`$LOG_FILE\`%0A%0A"
    MESSAGE+="_The database was NOT updated. Review first, then if legitimate:_%0A"
    MESSAGE+="\`sudo aide --update && sudo mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db\`"
    send_telegram "$MESSAGE"

else
    MESSAGE="✅ *AIDE Daily Check*%0A%0A"
    MESSAGE+="Server: $(hostname)%0A"
    MESSAGE+="Date: ${DATE_STAMP}%0A"
    MESSAGE+="Status: *No changes detected*%0A%0A"
    MESSAGE+="File integrity verified."
    send_telegram "$MESSAGE"

    # Only refresh the baseline when the check genuinely came back clean.
    $AIDE --update >/dev/null 2>&1
    mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db 2>/dev/null || true
fi

# Keep logs for 30 days
find /var/log -name "aide-check-*.log" -mtime +30 -delete 2>/dev/null || true
