#!/bin/bash
###############################################################################
# AIDE baseline refresh - check first, report what is absorbed, then update
#
# WHY THIS IS NOT JUST "aide --update"
#
# A file-integrity baseline is only worth something as a known-good reference.
# Refreshing it unconditionally - on a timer, or after every run that finds
# nothing - turns tampering into the new normal within one cycle. That is
# exactly the bug that made the previous AIDE reporter useless: it ran
# `aide --update` on every "clean" result, and the result was always "clean"
# because its parsing was broken.
#
# A stale database is noisy. An auto-refreshed one is silently blind. This
# script takes the third option: it never refreshes without first reporting
# what it is about to absorb.
#
#   1. aide --check
#   2. AIDE itself failed (exit >= 14)  -> alert, refresh NOTHING, exit 1
#   3. Differences found                -> send the full list, THEN refresh
#   4. No differences                   -> nothing to do
#
# Step 3 is the accountability: every refresh leaves a record of exactly which
# files it accepted. If something rode along with a package upgrade, it is in
# that message. Without the record this would just be auto-absorption with
# extra steps.
#
# WHEN TO RUN IT
#
# After a deliberate change: a package upgrade, a deployment, a config change.
# That is when the diff is expected and attributable to something you did.
# `aide --update` takes 10-20 minutes on a typical server, so this does not
# belong in an interactive hot path or after every apt transaction.
#
# Usage:
#   aide-refresh.sh              # check, report, refresh if there were changes
#   aide-refresh.sh --check-only # report only, never touch the database
#   aide-refresh.sh --reason "post apt upgrade"   # label the record
#
# Config, from /etc/server-baseline/selfcheck.env:
#   TELEGRAM_BOT_TOKEN=...
#   TELEGRAM_CHAT_ID=...
###############################################################################

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
set -u

# Credentials live with the project checkout, not in /etc. Resolution order:
#   1. $CONFIG_FILE                        explicit override
#   2. $ENV_FILE_DEFAULT                   absolute path recorded at install time
#   3. .env near this script                for running straight from the checkout
#   4. /etc/server-baseline/selfcheck.env  legacy location, still honoured
#
# The recorded path is the fragile part: move or re-clone the project and it
# stops resolving, which would make every alert silently stop. That is why
# security-selfcheck fails outright when no credentials resolve anywhere - the
# breakage shows up within a day instead of as permanent silence.
ENV_FILE_DEFAULT=""   # replaced with an absolute path at install time

resolve_env_file() {
    local self_dir c
    self_dir="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" 2>/dev/null && pwd)" || self_dir=""
    for c in "${CONFIG_FILE:-}" "$ENV_FILE_DEFAULT"              "$self_dir/.env" "$self_dir/../.env" "$self_dir/../../.env"              /etc/server-baseline/selfcheck.env; do
        if [ -n "$c" ] && [ -r "$c" ]; then echo "$c"; return 0; fi
    done
    return 1
}
CONFIG_FILE="$(resolve_env_file || true)"
[ -n "$CONFIG_FILE" ] && . "$CONFIG_FILE"

TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-${SECRET_TOKEN:-}}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-${CHAT_ID_PERSON1:-}}"

CHECK_ONLY=false
REASON="manual run"

while [ $# -gt 0 ]; do
    case "$1" in
        --check-only) CHECK_ONLY=true; shift ;;
        --reason)     REASON="${2:-manual run}"; shift 2 ;;
        --help|-h)    sed -n '2,44p' "$0"; exit 0 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root" >&2
    exit 1
fi

if ! command -v aide >/dev/null 2>&1; then
    echo "AIDE is not installed" >&2
    exit 0
fi

# On Debian and Ubuntu, `aide` does NOT read /etc/aide/aide.conf by itself.
# aide-common generates /var/lib/aide/aide.conf.autogenerated from that file
# plus /etc/aide/aide.conf.d/, and ships aide.wrapper to invoke it correctly.
# A bare `aide --check` therefore always fails with "missing configuration"
# (exit 17) on these distributions - which is indistinguishable from a broken
# config unless you know to look. Every AIDE call has to go through this.
aide_cmd() {
    if command -v aide.wrapper >/dev/null 2>&1; then
        echo "aide.wrapper"
    elif [ -x /usr/sbin/aide.wrapper ]; then
        echo "/usr/sbin/aide.wrapper"
    elif [ -f /var/lib/aide/aide.conf.autogenerated ]; then
        echo "aide --config=/var/lib/aide/aide.conf.autogenerated"
    elif [ -f /etc/aide/aide.conf ]; then
        echo "aide --config=/etc/aide/aide.conf"
    elif [ -f /etc/aide.conf ]; then
        echo "aide --config=/etc/aide.conf"
    fi
}
AIDE="$(aide_cmd)"

# Telegram's Markdown parser answers HTTP 400 on a single unmatched _ * ` or
# [ . These messages list file paths, where underscores are the norm, so every
# message that actually had content would have failed to send.
html_escape() {
    sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

LOG_FILE="/var/log/aide-refresh-$(date +%Y%m%d_%H%M%S).log"
HOST=$(hostname)
HOST_ESC=$(printf %s "$HOST" | html_escape)
TS=$(date '+%Y-%m-%d %H:%M')

syslog() {
    command -v logger >/dev/null 2>&1 && logger -t aide-refresh "$1"
    return 0
}

send_telegram() {
    if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
        syslog "no Telegram credentials; record not sent (it is still in $LOG_FILE)"
        return 1
    fi
    local code
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 \
        -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        -d chat_id="${TELEGRAM_CHAT_ID}" \
        -d parse_mode="HTML" \
        -d text="$1")
    [ "$code" = "200" ] && return 0
    syslog "Telegram send FAILED with HTTP ${code}"
    return 1
}

summary_count() {
    sed -n "s/^[[:space:]]*$1 entries:[[:space:]]*\([0-9][0-9]*\).*/\1/p" "$LOG_FILE" | head -1
}

# Checked here rather than at resolution time: syslog() is defined above this
# point, and a guard that calls a function declared later fails on the one path
# it exists to handle.
if [ -z "$AIDE" ]; then
    syslog "no usable AIDE configuration; nothing was checked or refreshed"
    echo "No usable AIDE configuration found - is aide-common installed?" >&2
    exit 1
fi

echo "Running aide --check (this takes a while)..."
$AIDE --check > "$LOG_FILE" 2>&1
RC=$?

###############################################################################
# AIDE itself failed - refresh nothing
###############################################################################
if [ "$RC" -ge 14 ]; then
    MSG="<b>🚨 AIDE REFRESH ABORTED</b>%0A%0A"
    MSG+="Server: <code>${HOST_ESC}</code>%0A"
    MSG+="Date: ${TS}%0A%0A"
    MSG+="<code>aide --check</code> failed with exit ${RC}. The database was <b>not</b> touched.%0A"
    MSG+="File integrity is currently UNVERIFIED - this is not a clean result.%0A%0A"
    MSG+="<pre>$(tail -5 "$LOG_FILE" | tr '\n' ' ' | cut -c1-250 | html_escape)</pre>"
    send_telegram "$MSG"
    syslog "aide --check failed with exit ${RC}; database untouched"
    echo "AIDE check failed (exit $RC). Database untouched. See $LOG_FILE" >&2
    exit 1
fi

###############################################################################
# No differences - nothing to absorb
###############################################################################
if [ "$RC" -eq 0 ]; then
    echo "No differences. Database already current."
    syslog "no differences; no refresh needed"
    exit 0
fi

###############################################################################
# Differences found - report exactly what, THEN refresh
###############################################################################
ADDED=$(summary_count Added);     ADDED=${ADDED:-0}
REMOVED=$(summary_count Removed); REMOVED=${REMOVED:-0}
CHANGED=$(summary_count Changed); CHANGED=${CHANGED:-0}

# AIDE detail lines look like "f++++++++++++++++: /path/to/file"
DETAIL=$(grep -E '^[^[:space:]]+: /' "$LOG_FILE" | head -25 | html_escape | sed 's/^/- /' | tr '\n' '@' | sed 's/@/%0A/g')
TOTAL_LINES=$(grep -cE '^[^[:space:]]+: /' "$LOG_FILE" 2>/dev/null)
TOTAL_LINES=${TOTAL_LINES:-0}

if [ "$CHECK_ONLY" = true ]; then
    MSG="<b>🔍 AIDE Check</b> (no refresh)%0A%0A"
else
    MSG="<b>📋 AIDE Baseline Refreshed</b>%0A%0A"
fi
MSG+="Server: <code>${HOST_ESC}</code>%0A"
MSG+="Date: ${TS}%0A"
MSG+="Reason: $(printf %s "$REASON" | html_escape)%0A%0A"
MSG+="Added: ${ADDED} / Removed: ${REMOVED} / Changed: ${CHANGED}%0A%0A"
MSG+="<b>Files:</b>%0A${DETAIL}%0A"
[ "$TOTAL_LINES" -gt 25 ] && MSG+="<i>...and $((TOTAL_LINES - 25)) more, see the log.</i>%0A"
MSG+="%0AFull log: <code>${LOG_FILE}</code>%0A%0A"

if [ "$CHECK_ONLY" = true ]; then
    MSG+="<i>The database was NOT updated (--check-only).</i>"
    send_telegram "$MSG"
    echo "Differences reported. Database untouched (--check-only). See $LOG_FILE"
    exit 2
fi

MSG+="<i>These files are now the new baseline. If anything above was not you, investigate before trusting the next check.</i>"

# Send the record BEFORE absorbing, so the evidence exists even if the update
# is interrupted.
send_telegram "$MSG"
syslog "absorbing ${ADDED} added / ${REMOVED} removed / ${CHANGED} changed (${REASON})"

echo "Refreshing baseline..."
if $AIDE --update >>"$LOG_FILE" 2>&1 || [ -f /var/lib/aide/aide.db.new ]; then
    if mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db 2>/dev/null; then
        echo "Baseline refreshed. Record sent."
        syslog "baseline refreshed"
        exit 0
    fi
fi

syslog "aide --update did not produce a new database"
echo "aide --update did not produce a new database - see $LOG_FILE" >&2
exit 1
