#!/bin/bash
###############################################################################
# Security Self-Check
#
# Answers one question: are the security controls on this host actually WORKING,
# or do they merely exist?
#
# Every check in here exists because the corresponding control was installed,
# reported healthy, and did nothing:
#   - fail2ban ran for months against a log file that no longer exists
#   - AIDE reported "no changes" while its own check was failing
#   - auditd was stopped by malware and nothing noticed
#   - a rootkit put itself in front of /usr/bin via /etc/profile
#
# "systemctl is-active" is not evidence. Each check below demands a real result.
#
# Usage:
#   sudo bash security-selfcheck.sh              # human-readable report
#   sudo bash security-selfcheck.sh --quiet      # only output when something is wrong
#   sudo bash security-selfcheck.sh --telegram   # send failures to Telegram
#   sudo bash security-selfcheck.sh --deep       # also run a full aide --check (10-20 min)
#
# Telegram credentials are read from /etc/server-baseline/selfcheck.env:
#   TELEGRAM_BOT_TOKEN=...
#   TELEGRAM_CHAT_ID=...
#
# Exit codes: 0 = all checks passed, 1 = at least one FAIL, 2 = only WARNs.
###############################################################################

# Reset PATH to system directories before doing anything else. If this host has
# a PATH hijack installed, inheriting the environment's PATH means running the
# attacker's replacements for the very tools used to detect them. Every command
# below is additionally invoked through an absolute path where it matters.
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

set -u

QUIET=false
TELEGRAM=false
DEEP=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --quiet)    QUIET=true; shift ;;
        --telegram) TELEGRAM=true; shift ;;
        --deep)     DEEP=true; shift ;;
        --help|-h)
            /bin/sed -n '2,30p' "$0"
            exit 0
            ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

FAILURES=()
WARNINGS=()
PASSES=()

pass() { PASSES+=("$1");   [ "$QUIET" = false ] && echo -e "  ${GREEN}[PASS]${NC} $1"; return 0; }
warn() { WARNINGS+=("$1"); [ "$QUIET" = false ] && echo -e "  ${YELLOW}[WARN]${NC} $1"; return 0; }
fail() { FAILURES+=("$1"); [ "$QUIET" = false ] && echo -e "  ${RED}[FAIL]${NC} $1"; return 0; }

section() { [ "$QUIET" = false ] && { echo ""; echo "── $1"; }; return 0; }

# On Debian and Ubuntu, `aide` does NOT read /etc/aide/aide.conf by itself.
# aide-common generates /var/lib/aide/aide.conf.autogenerated from that file
# plus /etc/aide/aide.conf.d/, and ships aide.wrapper to invoke it correctly.
# A bare `aide --check` therefore always fails with "missing configuration"
# (exit 17) on these distributions, which is indistinguishable from a genuinely
# broken config unless you know to look. Every AIDE call goes through this.
#
# Prints nothing when no usable configuration exists at all - typically because
# aide-common is missing, which is a different problem from a broken config and
# has a different fix.
aide_cmd() {
    if command -v aide.wrapper >/dev/null 2>&1; then
        echo "aide.wrapper"
    elif [ -x /usr/sbin/aide.wrapper ]; then
        echo "/usr/sbin/aide.wrapper"
    elif [ -f /var/lib/aide/aide.conf.autogenerated ]; then
        echo "aide --config=/var/lib/aide/aide.conf.autogenerated"
    elif [ -f /etc/aide/aide.conf ]; then
        echo "aide --config=/etc/aide/aide.conf"
    elif [ -f /etc/aide.conf ]; then
        echo "aide --config=/etc/aide.conf"
    fi
}

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root (sudo bash $0)" >&2
    exit 1
fi

[ "$QUIET" = false ] && {
    echo ""
    echo "=========================================================================="
    echo "  Security Self-Check - $(/bin/hostname) - $(/bin/date '+%Y-%m-%d %H:%M')"
    echo "=========================================================================="
}

###############################################################################
section "PATH integrity"
###############################################################################
# The single most characteristic sign of the userland rootkit families that ship
# with proxyjacking payloads: a directory prepended to PATH inside a system path,
# holding replacements for top/htop/lsof/crontab/df/mount/strace/ldd.
#
# $HOME/.local/bin in a user's own .profile is normal (pip, npm, XDG) and is not
# matched here - only .local/bin under a SYSTEM path is.

if /bin/grep -qs '/bin/\.local/bin\|/usr/bin/\.local/bin' \
        /etc/profile /etc/profile.d/* /etc/environment /etc/bash.bashrc /root/.bashrc /root/.profile 2>/dev/null; then
    fail "PATH injection found in a system profile (.local/bin under a system path)"
else
    pass "No PATH injection in system profiles"
fi

SHIMS_FOUND=""
for d in /usr/bin/.local /bin/.local; do
    [ -d "$d" ] && SHIMS_FOUND="$SHIMS_FOUND $d"
done
if [ -n "$SHIMS_FOUND" ]; then
    fail "Shim directory present:$SHIMS_FOUND"
else
    pass "No shim directories under /usr/bin or /bin"
fi

HIJACKED=""
for b in top htop lsof crontab df mount strace ldd; do
    RESOLVED=$(command -v "$b" 2>/dev/null || true)
    case "$RESOLVED" in
        /usr/bin/*|/bin/*|/usr/sbin/*|/sbin/*|"") : ;;
        *) HIJACKED="$HIJACKED $b->$RESOLVED" ;;
    esac
    for d in /usr/bin /bin; do
        [ -f "$d/.local/bin/$b" ] && HIJACKED="$HIJACKED $d/.local/bin/$b"
    done
done
if [ -n "$HIJACKED" ]; then
    fail "Diagnostic tools resolve to non-system paths:$HIJACKED"
else
    pass "Diagnostic tools resolve to system paths"
fi

###############################################################################
section "Fail2ban"
###############################################################################
# The failure this catches: a jail that is "enabled" but pointed at a log file
# that no longer exists. It starts, reports healthy, and bans nothing - which is
# indistinguishable from "no attacks" unless you compare against the journal.

if ! command -v fail2ban-client >/dev/null 2>&1; then
    warn "fail2ban is not installed"
elif ! /bin/systemctl is-active fail2ban >/dev/null 2>&1; then
    fail "fail2ban is installed but not running"
elif ! fail2ban-client status sshd >/dev/null 2>&1; then
    fail "fail2ban is running but the sshd jail is not active"
else
    pass "fail2ban sshd jail is active"

    # A jail reading /var/log/auth.log on Ubuntu 24.04 is a dead jail.
    if fail2ban-client get sshd logpath 2>/dev/null | /bin/grep -q '/var/log/auth.log' && \
       [ ! -s /var/log/auth.log ]; then
        fail "sshd jail reads /var/log/auth.log, which does not exist on this system - it can never ban"
    else
        pass "sshd jail log source exists"
    fi

    # Ask fail2ban what it actually RESOLVED, not what the files say. The read
    # order is jail.conf -> jail.d/*.conf -> jail.local -> jail.d/*.local, so a
    # jail.local can silently override everything in jail.d/*.conf. A set
    # journalmatch is proof that the systemd backend survived that resolution.
    if fail2ban-client get sshd journalmatch 2>/dev/null | /bin/grep -q '_SYSTEMD_UNIT'; then
        pass "sshd jail resolved to the systemd backend (journalmatch is set)"
    else
        fail "sshd jail did NOT resolve to the systemd backend - it is reading a file, not the journal"
        if [ -f /etc/fail2ban/jail.local ] && /bin/grep -q '^\[sshd\]' /etc/fail2ban/jail.local 2>/dev/null; then
            warn "  /etc/fail2ban/jail.local defines [sshd] and is read AFTER jail.d/*.conf - it wins"
        fi
        if ! python3 -c "import systemd.journal" >/dev/null 2>&1; then
            warn "  python3-systemd is missing; the systemd backend cannot initialise"
            warn "  Fix: apt-get install -y python3-systemd && systemctl restart fail2ban"
        fi
        warn "  Inspect the resolved config with: fail2ban-client -d | grep sshd"
    fi

    # Compare bans against actual failed logins. Zero bans while the journal is
    # full of failures is a fault, not quiet.
    # Note: `grep -c` prints 0 AND exits 1 on no match, so `|| echo 0` would
    # produce "0\n0" and break the numeric test. wc -l always exits 0.
    #
    # Both counters must cover the SAME window. fail2ban's totals reset when the
    # service restarts, so comparing them against a fixed 7-day journal count
    # reports a freshly restarted jail as broken - which is exactly what this
    # check did on its first real run.
    F2B_STATUS=$(fail2ban-client status sshd 2>/dev/null)
    BANS=$(echo "$F2B_STATUS" | /bin/grep -i 'Total banned' | /bin/grep -oE '[0-9]+$' | /usr/bin/head -1)
    BANS=${BANS:-0}
    SEEN=$(echo "$F2B_STATUS" | /bin/grep -i 'Total failed' | /bin/grep -oE '[0-9]+$' | /usr/bin/head -1)
    SEEN=${SEEN:-0}

    # Count the journal over the jail's own uptime, not an arbitrary week.
    F2B_SINCE=$(/bin/systemctl show fail2ban --property=ActiveEnterTimestamp --value 2>/dev/null)
    if [ -n "$F2B_SINCE" ]; then
        ATTEMPTS=$(/bin/journalctl -u ssh --since "$F2B_SINCE" --no-pager 2>/dev/null | \
                   /bin/grep -iE 'Failed password|Invalid user|authentication failure' | /usr/bin/wc -l)
    else
        ATTEMPTS=0
    fi
    ATTEMPTS=${ATTEMPTS:-0}
    # Zero bans is the obvious failure. A handful of bans against thousands of
    # attempts is the same failure wearing a disguise: the jail is technically
    # alive but is not seeing most of what reaches sshd. With maxretry=3, even
    # allowing for repeat offenders being banned once, the ratio should not be
    # anywhere near this lopsided.
    # Two separate questions, in order:
    #   1. Is the jail SEEING what the journal sees? (reading the right source)
    #   2. Having seen them, is it BANNING? (acting on what it reads)
    if [ "$ATTEMPTS" -gt 20 ] && [ "$SEEN" -eq 0 ]; then
        fail "The journal shows $ATTEMPTS failed logins since fail2ban started, but the jail has seen 0"
        warn "  It is running against the wrong source. Check: fail2ban-client get sshd logpath"
    elif [ "$SEEN" -gt 30 ] && [ "$BANS" -eq 0 ]; then
        fail "The jail registered $SEEN failures but banned nothing - it reads but does not act"
        warn "  Check maxretry/findtime: fail2ban-client get sshd maxretry"
    elif [ "$SEEN" -gt 0 ] || [ "$BANS" -gt 0 ]; then
        pass "Jail has seen $SEEN failures and issued $BANS ban(s) since it started"
    else
        pass "No failed logins since fail2ban started - nothing to judge yet"
    fi
fi

###############################################################################
section "SSH listening ports"
###############################################################################
# Port 22 is kept open on purpose as a lockout fallback, but it is meant to be
# temporary and it is easy to leave open forever. This reports what sshd is
# actually bound to, which is not always what sshd_config appears to say -
# socket activation, drop-in files under sshd_config.d and a stale ssh.socket
# all override it.

SSH_PORTS=$(/bin/ss -tlnp 2>/dev/null | /bin/grep -i sshd | \
            /bin/grep -oE ':[0-9]+ ' | /bin/tr -d ': ' | sort -u | /bin/tr '\n' ' ')
SSH_PORTS=${SSH_PORTS:-none}

if [ "$SSH_PORTS" = "none" ]; then
    warn "Could not determine which ports sshd is listening on"
elif echo "$SSH_PORTS" | /bin/grep -qw 22; then
    if echo "$SSH_PORTS" | /bin/grep -qw 888; then
        warn "sshd listens on: $SSH_PORTS - port 22 is still open alongside 888"
        warn "  Close it only from a SECOND session after verifying 888 works:"
        warn "  sudo sed -i '/^Port 22\$/d' /etc/ssh/sshd_config && sudo systemctl restart ssh"
    else
        warn "sshd listens on port 22 only - the hardened port 888 is not active"
    fi
else
    pass "sshd listens on: $SSH_PORTS (port 22 is closed)"
fi

# Where is the port actually configured? On a socket-activated host the Port
# directive in sshd_config is ignored entirely, so a leftover "Port 22" there is
# both misleading and a trap: deleting it looks like it closed the port when it
# changed nothing at all.
SOCKET_ON=false
/bin/systemctl is-active ssh.socket >/dev/null 2>&1 && SOCKET_ON=true
CONF_PORTS=$(/bin/grep -oE '^Port +[0-9]+' /etc/ssh/sshd_config 2>/dev/null | /bin/grep -oE '[0-9]+' | sort -u | /bin/tr '\n' ' ')

if [ "$SOCKET_ON" = true ]; then
    if [ -n "$CONF_PORTS" ]; then
        warn "Socket activation is in use, but sshd_config still sets Port: $CONF_PORTS"
        warn "  Those lines are IGNORED. Editing them will not change anything."
        warn "  The real ports live in /etc/systemd/system/ssh.socket.d/ports.conf"
    else
        pass "Port configured in one place only (ssh.socket)"
    fi
elif [ -f /etc/systemd/system/ssh.socket.d/ports.conf ]; then
    warn "sshd_config is authoritative, but a stale ssh.socket.d/ports.conf exists"
    warn "  It would take over if socket activation is ever enabled. Remove it."
else
    pass "Port configured in one place only (sshd_config)"
fi

if [ -n "${SSH_PORTS##*none*}" ]; then
    UNEXPECTED_SSH=""
    for p in $SSH_PORTS; do
        case "$p" in
            22|888) : ;;
            *) UNEXPECTED_SSH="$UNEXPECTED_SSH $p" ;;
        esac
    done
    if [ -n "$UNEXPECTED_SSH" ]; then
        fail "sshd listens on unexpected port(s):$UNEXPECTED_SSH"
    fi
fi

###############################################################################
section "Listeners on all interfaces"
###############################################################################
# Everything bound to 0.0.0.0 or :: is reachable from the internet unless a
# firewall stops it - and for container ports, UFW does not. This inventories
# what is exposed and flags anything outside the expected set.
#
# Expected: SSH (22, 888) and, when not in Cloudflare-only mode, HTTP/HTTPS.
# Everything else is worth a second look, especially management interfaces:
# 9443 Portainer, 8000 Portainer agent, 19999 Netdata, 8120 the bot API.

EXPECTED_PUBLIC="22 888 80 443"
MGMT_PORTS="9443 8000 19999 8120 2375 2376 5432 3306 6379 27017"

PUBLIC_LISTENERS=$(/bin/ss -tlnH 2>/dev/null | \
    /usr/bin/awk '{print $4}' | \
    /bin/grep -E '^(0\.0\.0\.0|\*|\[::\]):' | \
    /bin/grep -oE '[0-9]+$' | sort -un)

if [ -z "$PUBLIC_LISTENERS" ]; then
    pass "Nothing is listening on all interfaces"
else
    UNEXPECTED=""
    MGMT_EXPOSED=""
    for p in $PUBLIC_LISTENERS; do
        case " $EXPECTED_PUBLIC " in *" $p "*) continue ;; esac
        case " $MGMT_PORTS " in
            *" $p "*) MGMT_EXPOSED="$MGMT_EXPOSED $p"; continue ;;
        esac
        UNEXPECTED="$UNEXPECTED $p"
    done

    # Informational, not a verdict - the verdicts follow below.
    [ "$QUIET" = false ] && \
        echo "  ---- open on all interfaces: $(echo "$PUBLIC_LISTENERS" | /bin/tr '\n' ' ')"

    if [ -z "$MGMT_EXPOSED" ] && [ -z "$UNEXPECTED" ]; then
        pass "Only expected ports (SSH, HTTP/HTTPS) are open on all interfaces"
    fi

    if [ -n "$MGMT_EXPOSED" ]; then
        fail "Management interface exposed on all interfaces:$MGMT_EXPOSED"
        for p in $MGMT_EXPOSED; do
            OWNER=$(/bin/ss -tlnpH "sport = :$p" 2>/dev/null | \
                    /bin/grep -oE 'users:\(\("[^"]+"' | /bin/grep -oE '"[^"]+"' | /bin/tr -d '"' | head -1)
            warn "  port $p -> ${OWNER:-unknown}. Bind it to 127.0.0.1 and reach it through a tunnel."
        done
    fi

    if [ -n "$UNEXPECTED" ]; then
        warn "Other ports open on all interfaces:$UNEXPECTED (verify each is intended)"
    fi

    # Container-published ports are the ones UFW does not gate.
    if command -v docker >/dev/null 2>&1; then
        if ! /usr/sbin/iptables -L DOCKER-USER -n 2>/dev/null | /bin/grep -q DROP; then
            if docker ps --format '{{.Ports}}' 2>/dev/null | /bin/grep -qE '0\.0\.0\.0:|:::'; then
                fail "Containers publish on all interfaces and DOCKER-USER has no DROP rule"
                warn "  UFW does not filter these. Verify from ANOTHER machine, not from here."
            fi
        fi
    fi
fi

###############################################################################
section "auditd and process accounting"
###############################################################################
# auditd being stopped was the clearest signal in the AC2 incident and nothing
# reported it. This check is the alert that was missing.

if ! command -v auditctl >/dev/null 2>&1; then
    warn "auditd is not installed"
else
    if /bin/systemctl is-active auditd >/dev/null 2>&1; then
        pass "auditd is running"
    else
        fail "auditd is NOT running - syscall auditing is off"
    fi

    RULE_COUNT=$(auditctl -l 2>/dev/null | /usr/bin/wc -l)
    RULE_COUNT=${RULE_COUNT:-0}
    if [ "${RULE_COUNT:-0}" -lt 10 ]; then
        fail "auditd has only ${RULE_COUNT} rules loaded - expected 30+"
    else
        pass "auditd has ${RULE_COUNT} rules loaded"
    fi

    # Persistence paths must actually be covered, not merely present in a file.
    MISSING_WATCH=""
    for p in /etc/profile /etc/cron.d /var/spool/cron/crontabs /etc/systemd/system /root/.ssh /etc/ld.so.preload; do
        auditctl -l 2>/dev/null | /bin/grep -q -- "-w $p" || MISSING_WATCH="$MISSING_WATCH $p"
    done
    if [ -n "$MISSING_WATCH" ]; then
        warn "No audit watch on:$MISSING_WATCH"
    else
        pass "Persistence paths are covered by audit watches"
    fi

    # An auditd that stopped in the recent past is worth knowing about even if
    # it is running now.
    if /bin/journalctl -u auditd --since "-30 days" --no-pager 2>/dev/null | \
            /bin/grep -qiE 'stopped|exiting'; then
        warn "auditd was stopped at least once in the last 30 days - check: journalctl -u auditd"
    else
        pass "No auditd stop events in the last 30 days"
    fi
fi

if /bin/systemctl is-active acct >/dev/null 2>&1 || /bin/systemctl is-active psacct >/dev/null 2>&1; then
    pass "Process accounting is active"
else
    warn "Process accounting (acct) is not active - no command history will be recorded"
fi

###############################################################################
section "File integrity (AIDE)"
###############################################################################
# Catches the state where AIDE is installed, the cron job runs, and every report
# is green because the check itself is failing.

AIDE_CMD=$(aide_cmd)

if ! command -v aide >/dev/null 2>&1; then
    warn "AIDE is not installed"
elif [ -z "$AIDE_CMD" ]; then
    # The aide binary exists but the Debian/Ubuntu configuration layer does not.
    # Nothing can run in this state - it is not a broken config, it is an absent
    # one, and it means AIDE has never produced a result on this host.
    fail "AIDE is installed but has no usable configuration - it cannot run at all"
    warn "  No aide.wrapper, no /var/lib/aide/aide.conf.autogenerated, no /etc/aide/aide.conf."
    warn "  Almost always: the aide-common package is missing."
    warn "  Fix: apt-get install -y aide-common && aideinit"
elif ! $AIDE_CMD --config-check >/dev/null 2>&1; then
    # A broken config means every scheduled run aborts. Reported here because
    # the failure is otherwise invisible: an aborted check produces no findings,
    # which reads exactly like a clean result.
    fail "aide --config-check fails - the configuration is broken, no scan can run"
    warn "  See: sudo $AIDE_CMD --config-check"
elif [ ! -f /var/lib/aide/aide.db ]; then
    fail "AIDE is installed but has no database - it has never had a baseline"
else
    DB_AGE_DAYS=$(( ( $(/bin/date +%s) - $(/usr/bin/stat -c %Y /var/lib/aide/aide.db) ) / 86400 ))
    if [ "$DB_AGE_DAYS" -gt 30 ]; then
        warn "AIDE database is ${DB_AGE_DAYS} days old - stale baselines produce noise, then get ignored"
    else
        pass "AIDE database is ${DB_AGE_DAYS} days old"
    fi

    # Deliberately NOT running a full `aide --check` here. It takes 10-20
    # minutes, and a daily check that costs twenty minutes gets switched off
    # within a week - at which point this whole script stops running too.
    #
    # The evidence that AIDE completes is in the last scheduled run's log,
    # which is the same reasoning applied to rkhunter. --deep forces a real
    # check for when you want one.
    # Only consider logs written AFTER the current database. A rebuild makes
    # every earlier log irrelevant: they describe a baseline that no longer
    # exists, and judging the present by them reports failures that were
    # already fixed.
    # The installed reporter resolves AIDE independently of this script. That
    # logic lived in five places and drifted: one copy lacked a branch, fell
    # through to a bare `aide`, and reported exit 17 every night on a host whose
    # configuration was fine. Compare what the reporter would resolve against
    # what this script resolves, so a future divergence is caught here rather
    # than by a nightly alert nobody can act on.
    if [ -f /usr/local/bin/aide-telegram.sh ] && \
       ! /bin/grep -q 'config=/etc/aide/aide.conf' /usr/local/bin/aide-telegram.sh 2>/dev/null; then
        fail "The installed AIDE reporter cannot resolve this host's config layout"
        warn "  It will report exit 17 nightly regardless of the actual state."
        warn "  Fix: sudo update-baseline   (refreshes the reporter from the checkout)"
    fi

    # A log only says something about the present if it was written BOTH after
    # the current database AND by the current reporter. A log from the old
    # broken reporter post-dates the database on any host where the database
    # was never rebuilt, and reporting its error describes a defect that has
    # since been fixed.
    AIDE_CUTOFF=/var/lib/aide/aide.db
    if [ -f /usr/local/bin/aide-telegram.sh ] &&        [ /usr/local/bin/aide-telegram.sh -nt /var/lib/aide/aide.db ]; then
        AIDE_CUTOFF=/usr/local/bin/aide-telegram.sh
    fi
    LAST_AIDE_LOG=$(/usr/bin/find /var/log -maxdepth 1                         \( -name 'aide-check-*.log' -o -name 'aide-refresh-*.log' \)                         -newer "$AIDE_CUTOFF" 2>/dev/null |                     /usr/bin/xargs -r /bin/ls -1t 2>/dev/null | /usr/bin/head -1)

    if [ "$DEEP" = true ]; then
        echo "  ---- running a full aide --check (10-20 minutes)..."
        $AIDE_CMD --check >/dev/null 2>&1
        AIDE_RC=$?
        if [ "$AIDE_RC" -ge 14 ]; then
            fail "aide --check fails with exit ${AIDE_RC} - file integrity is UNVERIFIED"
        elif [ "$AIDE_RC" -ne 0 ]; then
            warn "aide --check reports differences (exit ${AIDE_RC}) - review them"
        else
            pass "aide --check completes cleanly"
        fi
    elif [ -z "$LAST_AIDE_LOG" ]; then
        warn "No AIDE run since the current setup was put in place - the first scheduled check is pending"
        warn "  Verify once with: sudo security-selfcheck --deep   (takes 10-20 minutes)"
    else
        LOG_AGE_DAYS=$(( ( $(/bin/date +%s) - $(/usr/bin/stat -c %Y "$LAST_AIDE_LOG") ) / 86400 ))
        if [ "$LOG_AGE_DAYS" -gt 3 ]; then
            fail "The last AIDE run was ${LOG_AGE_DAYS} days ago - the scheduled check is not running"
        elif /bin/grep -qE '^(ERROR|.*missing configuration|.*Invalid configure|.*Configuration error)' "$LAST_AIDE_LOG" 2>/dev/null; then
            fail "The last AIDE run ended in an error - integrity is UNVERIFIED"
            warn "  See: $LAST_AIDE_LOG"
        else
            pass "AIDE ran ${LOG_AGE_DAYS} day(s) ago and completed"
        fi
    fi
fi

###############################################################################
section "Rootkit scanning (rkhunter)"
###############################################################################
# The failure this catches: rkhunter installed, cron job firing daily, and every
# report green - because the scan aborts on a configuration error before it
# checks anything. No warnings in the log is not the same as no findings.

if ! command -v rkhunter >/dev/null 2>&1; then
    warn "rkhunter is not installed"
else
    if /usr/bin/rkhunter --config-check >/dev/null 2>&1; then
        pass "rkhunter configuration is valid"
    else
        fail "rkhunter --config-check fails - scans abort before checking anything"
        warn "  See: sudo rkhunter --config-check"
    fi

    # Did the most recent scan actually run to completion? The summary line is
    # the evidence; its absence means the log holds errors, not results.
    RK_LOG=""
    for f in /var/log/rkhunter.log /var/log/rkhunter/rkhunter.log; do
        [ -f "$f" ] && RK_LOG="$f" && break
    done

    if [ -z "$RK_LOG" ]; then
        warn "No rkhunter log found - it may never have run"
    else
        RK_AGE_DAYS=$(( ( $(/bin/date +%s) - $(/usr/bin/stat -c %Y "$RK_LOG") ) / 86400 ))
        if [ "$RK_AGE_DAYS" -gt 8 ]; then
            fail "rkhunter last wrote its log ${RK_AGE_DAYS} days ago - it is not running on schedule"
        else
            pass "rkhunter log is ${RK_AGE_DAYS} days old"
        fi

        if /bin/grep -q "System checks summary" "$RK_LOG" 2>/dev/null; then
            RK_WARN=$(/bin/grep -c "^Warning:" "$RK_LOG" 2>/dev/null || true)
            if [ "${RK_WARN:-0}" -gt 0 ]; then
                warn "Last rkhunter scan completed with ${RK_WARN} warning(s) - review $RK_LOG"
            else
                pass "Last rkhunter scan ran to completion with no warnings"
            fi
        else
            fail "The rkhunter log contains no completed scan - only errors or partial output"
            warn "  This host is NOT being scanned for rootkits. Check: sudo rkhunter --config-check"
        fi
    fi

    # An installed reporter with the counting bug reports green on an aborted scan.
    if [ -f /usr/local/bin/rkhunter-telegram.sh ] && \
       /bin/grep -q -- '--report-warnings-only' /usr/local/bin/rkhunter-telegram.sh 2>/dev/null && \
       ! /bin/grep -q 'System checks summary' /usr/local/bin/rkhunter-telegram.sh 2>/dev/null; then
        fail "rkhunter-telegram.sh cannot distinguish an aborted scan from a clean one"
        warn "  It reports '✅ All Clear' when the scan never ran. Re-run the installer's security section."
    fi
fi

###############################################################################
section "Reporters can actually report"
#
# Two bugs of this shape have shipped already: rkhunter-telegram.sh built its
# "All Clear" message and never sent it, and lynis-telegram.sh curled with
# >/dev/null 2>&1 so a rejected message looked exactly like a delivered one.
#
# Both were invisible from the outside, because the symptom of a broken
# reporter is silence - and silence is also what a healthy quiet week looks
# like. These are static checks on the installed copies: cheap, and they fire
# the same day the file drifts rather than the day you need the alert.
###############################################################################

for REP in /usr/local/bin/aide-telegram.sh /usr/local/bin/rkhunter-telegram.sh \
           /usr/local/bin/lynis-telegram.sh /usr/local/bin/aide-refresh.sh; do
    [ -f "$REP" ] || continue
    REP_NAME="$(basename "$REP")"

    # Talks to Telegram without ever looking at the HTTP status.
    if /bin/grep -q 'api\.telegram\.org' "$REP" 2>/dev/null && \
       ! /bin/grep -q 'http_code\|%{http_code}' "$REP" 2>/dev/null; then
        fail "$REP_NAME sends without checking the result - a rejected report looks delivered"
    fi

    # Builds a message it never sends. Counting is deliberate rather than
    # exact: a reporter that assembles several messages and sends fewer times
    # than it has branches is worth a look either way.
    REP_BUILDS=$(/bin/grep -c '^[[:space:]]*MESSAGE="' "$REP" 2>/dev/null || true)
    REP_SENDS=$(/bin/grep -c '^[[:space:]]*send_telegram "' "$REP" 2>/dev/null || true)
    if [ "${REP_BUILDS:-0}" -gt 0 ] && [ "${REP_SENDS:-0}" -eq 0 ]; then
        fail "$REP_NAME builds a report but never calls send_telegram - it is silent by construction"
    elif [ "${REP_BUILDS:-0}" -gt 1 ] && [ "${REP_SENDS:-0}" -gt 1 ] && \
         [ "${REP_SENDS:-0}" -lt "${REP_BUILDS:-0}" ]; then
        warn "$REP_NAME has ${REP_BUILDS} message branches but only ${REP_SENDS} sends - one path may be silent"
    fi
done

###############################################################################
section "Writable filesystem hardening"
###############################################################################

for m in /tmp /var/tmp /dev/shm; do
    if /bin/findmnt -no OPTIONS "$m" 2>/dev/null | /bin/grep -q noexec; then
        pass "$m is mounted noexec"
    else
        warn "$m is executable - payloads dropped there can be run directly"
    fi
done

TMP_EXEC=$(/usr/bin/find /tmp /var/tmp /dev/shm -maxdepth 2 -type f -executable 2>/dev/null | /usr/bin/head -5)
if [ -n "$TMP_EXEC" ]; then
    fail "Executable files present in temporary directories: $(echo "$TMP_EXEC" | /bin/tr '\n' ' ')"
else
    pass "No executable files in /tmp, /var/tmp, /dev/shm"
fi

###############################################################################
section "Docker exposure"
###############################################################################

if command -v docker >/dev/null 2>&1; then
    # A second daemon with its own data-root is how container workloads are
    # hidden from `docker ps` - not by filtering output, but by running on a
    # completely separate daemon.
    EXTRA_DAEMONS=$(/bin/ps -eo args 2>/dev/null | \
        /bin/grep -E '(^|/)(dockerd|containerd)( |$)' | \
        /bin/grep -v grep | \
        /bin/grep -vE -- '-H fd://|--config /etc/containerd|^/usr/bin/containerd$|containerd-shim' || true)
    if [ -n "$EXTRA_DAEMONS" ]; then
        fail "Unexpected dockerd/containerd process: $(echo "$EXTRA_DAEMONS" | /usr/bin/head -2 | /bin/tr '\n' ' ')"
    else
        pass "No unexpected Docker daemons"
    fi

    # Container ports published on all interfaces. These are reachable from the
    # internet whatever UFW says.
    PUBLIC_PORTS=$(docker ps --format '{{.Names}} {{.Ports}}' 2>/dev/null | /bin/grep -E '0\.0\.0\.0:|:::' || true)
    if [ -n "$PUBLIC_PORTS" ]; then
        if /usr/sbin/iptables -L DOCKER-USER -n 2>/dev/null | /bin/grep -q DROP; then
            pass "Containers publish on 0.0.0.0 but DOCKER-USER has a DROP rule"
        else
            warn "Containers published on all interfaces with no DOCKER-USER filter: $(echo "$PUBLIC_PORTS" | /bin/tr '\n' '; ')"
        fi
    else
        pass "No containers published on all interfaces"
    fi

    # Known proxyjacking images.
    PROXYWARE=$(docker ps -a --format '{{.Names}} {{.Image}}' 2>/dev/null | \
        /bin/grep -iE 'repocket|packetstream|psclient|bitping|proxyrack|earnfm|wipter|antgain|traffmonetizer|pawns|honeygain|peer2profit' || true)
    if [ -n "$PROXYWARE" ]; then
        fail "Proxyware container present: $PROXYWARE"
    else
        pass "No known proxyware containers"
    fi

    # Containers holding root-equivalent access to the host.
    for c in $(docker ps --format '{{.Names}}' 2>/dev/null); do
        PRIV=$(docker inspect --format='{{.HostConfig.Privileged}}' "$c" 2>/dev/null)
        PIDMODE=$(docker inspect --format='{{.HostConfig.PidMode}}' "$c" 2>/dev/null)
        SOCK=$(docker inspect --format='{{range .Mounts}}{{.Source}} {{end}}' "$c" 2>/dev/null | /bin/grep -o 'docker.sock' | /usr/bin/wc -l)
        RISK=""
        [ "$PRIV" = "true" ] && RISK="$RISK privileged"
        [ "$PIDMODE" = "host" ] && RISK="$RISK pid=host"
        [ "${SOCK:-0}" -gt 0 ] && RISK="$RISK docker.sock"
        if [ -n "$RISK" ]; then
            warn "Container '$c' has host-level access:$RISK"
        fi
    done
else
    pass "Docker is not installed"
fi

###############################################################################
section "Persistence artefacts"
###############################################################################

if /bin/grep -rqs 'perfcc\|FPROF' /root/.profile /root/.bashrc /etc/cron.d/ \
        /etc/cron.hourly/ /etc/cron.daily/ /var/spool/cron/crontabs/ 2>/dev/null; then
    fail "perfctl-style persistence marker found (perfcc/FPROF)"
else
    pass "No perfctl-style persistence markers"
fi

HIDDEN_DIRS=$(/bin/ls -d /var/.i.* /tmp/.t.* /usr/bin/wbin /bin/wbin /usr/lib/exi /dev/shm/.config /root/.config/cron 2>/dev/null || true)
if [ -n "$HIDDEN_DIRS" ]; then
    fail "Hidden working directory present: $(echo "$HIDDEN_DIRS" | /bin/tr '\n' ' ')"
else
    pass "No known hidden working directories"
fi

if [ -s /etc/ld.so.preload ]; then
    fail "/etc/ld.so.preload is non-empty: $(/bin/cat /etc/ld.so.preload | /bin/tr '\n' ' ')"
else
    pass "/etc/ld.so.preload is empty"
fi

###############################################################################
section "Alerting is able to alert"
###############################################################################
# The credential file lives with the project checkout. That makes it easy to
# find and impossible to commit, but it also means moving or re-cloning the
# checkout silently detaches every scheduled alert from its credentials.
#
# This check is what makes that survivable: a detached alerting stack shows up
# here within a day, instead of as permanent silence that reads exactly like
# "nothing to report".

# Resolve the same way the installed scripts do: read back the path they
# recorded, rather than assuming a location.
ALERT_ENV=""
if [ -f /usr/local/bin/security-watchdog.sh ]; then
    ALERT_ENV=$(/bin/grep -oP '^ENV_FILE_DEFAULT="\K[^"]+' /usr/local/bin/security-watchdog.sh 2>/dev/null | head -1)
fi
[ -z "$ALERT_ENV" ] && [ -r /etc/server-baseline/selfcheck.env ] && ALERT_ENV=/etc/server-baseline/selfcheck.env

if [ ! -f /usr/local/bin/security-watchdog.sh ]; then
    warn "Security watchdog is not installed - no state-change alerting on this host"
elif [ -z "$ALERT_ENV" ]; then
    fail "The watchdog has no credential file recorded - it can never alert"
    warn "  Re-run update-baseline.sh; section 0 records the path."
elif [ ! -r "$ALERT_ENV" ]; then
    fail "Alert credentials are missing: $ALERT_ENV does not exist"
    warn "  The watchdog and the daily reports run but send nothing."
    warn "  Usually means the project checkout moved or was re-cloned without .env."
elif ! /bin/grep -q 'TELEGRAM_BOT_TOKEN=.' "$ALERT_ENV" 2>/dev/null; then
    fail "$ALERT_ENV exists but holds no bot token - alerting is silent"
else
    pass "Alert credentials resolve ($ALERT_ENV)"
    PERMS=$(/usr/bin/stat -c %a "$ALERT_ENV" 2>/dev/null)
    if [ "$PERMS" != "600" ] && [ "$PERMS" != "400" ]; then
        warn "  $ALERT_ENV is mode $PERMS - should be 600"
    fi
fi

###############################################################################
section "Secrets exposure"
###############################################################################
# Tokens on a command line are readable by anything that can read /proc,
# including any container running with pid: host.

# Report WHICH process and WHICH flag - never the value. This report gets piped
# to a file and pasted into tickets; printing the secret would copy it to every
# one of those places, which is the problem it is reporting.
# Capture the process list BEFORE the filter runs. In a pipeline both sides run
# concurrently, so grep's own argv - which contains the patterns being searched
# for - shows up in ps output and the check reports itself as a finding.
PS_SNAPSHOT=$(/bin/ps -eo comm=,args= 2>/dev/null)

CMDLINE_SECRETS=$(echo "$PS_SNAPSHOT" | \
    /bin/grep -iE -- '--token[= ]|--password[= ]|apikey=|api_key=|--secret[= ]' | \
    /bin/grep -v grep | \
    /usr/bin/awk '{proc=$1; flag="unknown";
                   if ($0 ~ /--token/)    flag="--token";
                   if ($0 ~ /--password/) flag="--password";
                   if ($0 ~ /[aA][pP][iI]_?[kK][eE][yY]=/) flag="apikey=";
                   if ($0 ~ /--secret/)   flag="--secret";
                   print proc" ("flag")"}' | sort -u | /bin/tr '\n' ' ' || true)

if [ -n "$CMDLINE_SECRETS" ]; then
    fail "Secret on a process command line: $CMDLINE_SECRETS"
    warn "  Value withheld on purpose. Inspect yourself with: ps -eo args | grep <process>"
    warn "  Readable via /proc by anything on this host, including a pid:host container."
else
    pass "No secrets on process command lines"
fi

###############################################################################
# Report
###############################################################################

TOTAL=$(( ${#PASSES[@]} + ${#WARNINGS[@]} + ${#FAILURES[@]} ))

if [ "$QUIET" = false ]; then
    echo ""
    echo "=========================================================================="
    echo "  ${#PASSES[@]} passed, ${#WARNINGS[@]} warnings, ${#FAILURES[@]} failures (of $TOTAL checks)"
    echo "=========================================================================="
    echo ""
fi

if [ ${#FAILURES[@]} -gt 0 ] || [ ${#WARNINGS[@]} -gt 0 ]; then
    if [ "$QUIET" = true ]; then
        echo "Security self-check on $(/bin/hostname): ${#FAILURES[@]} failures, ${#WARNINGS[@]} warnings"
        for f in "${FAILURES[@]}"; do echo "  [FAIL] $f"; done
        for w in "${WARNINGS[@]}"; do echo "  [WARN] $w"; done
    fi

    if [ "$TELEGRAM" = true ] && [ -r /etc/server-baseline/selfcheck.env ]; then
        # shellcheck disable=SC1091
        . /etc/server-baseline/selfcheck.env
        if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
            MSG="🔍 *Security Self-Check*%0A%0A"
            MSG+="Server: $(/bin/hostname)%0A"
            MSG+="Date: $(/bin/date '+%Y-%m-%d %H:%M')%0A%0A"
            MSG+="Failures: ${#FAILURES[@]} • Warnings: ${#WARNINGS[@]}%0A%0A"
            for f in "${FAILURES[@]}"; do MSG+="🚨 ${f}%0A"; done
            for w in "${WARNINGS[@]}"; do MSG+="⚠️ ${w}%0A"; done
            /usr/bin/curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                -d chat_id="${TELEGRAM_CHAT_ID}" \
                -d text="${MSG}" \
                -d parse_mode="Markdown" >/dev/null 2>&1
        fi
    fi
fi

[ ${#FAILURES[@]} -gt 0 ] && exit 1
[ ${#WARNINGS[@]} -gt 0 ] && exit 2
exit 0
